map:
  frame_id: map
  layers: [ elevation, obstacle ]
  default_values: [ 0.0, 0.0 ]
  resolution: 0.5
  position:
    x: 0.0
    y: 0.0
  length: 30.0  # x dimension
  width: 30.0  # y dimension
  topic: grid_map